apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: web
spec:
  selector:
    matchLabels:
      mylabel: MyNginx
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        mylabel: MyNginx
    spec:
      hostNetwork: false
      initContainers:
        - name: init-nginx
          image: busybox
          command: ['sh', '-c', "env > /usr/share/nginx/html/index.html"]
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-cache
      containers:
        - name: nginx
          image: arm64v8/nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-cache
      volumes:
        - name: nginx-cache
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname