apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  # loadBalancerIP: 192.168.86.240
  selector:
    app: web
    mylabel: MyNginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30080